In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os 
os.path.dirname(os.path.abspath("__file__"))

'd:\\Facultate\\PhD\\work\\learning_stuff\\dqn_clean\\minatar_work'

In [2]:
import my_dqn

c:\Users\Marius\anaconda3\envs\general\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a = [1]

a[-1]

1

In [3]:
from minatar import Environment

game = "breakout"
env = Environment(game)

my_agent = my_dqn.AgentDQN(env, "file_name", False, "")

In [4]:
my_agent.train(10, 10000)

INFO:root:Avg return: 0.0 | Time per frame: 0.00021054479810926648


In [5]:
current_state = my_dqn.get_state(my_agent.env.state())

current_state.size()

torch.Size([1, 4, 10, 10])

In [6]:
import torch

In [8]:
sample = my_agent.replay_buffer.sample(my_agent.batch_size)

state, action, reward, next_state, terminated = sample

state = torch.from_numpy(state)
next_state = torch.from_numpy(next_state)
action = torch.LongTensor(action).unsqueeze(1)
reward = torch.FloatTensor(reward).unsqueeze(1)
terminated = torch.FloatTensor(terminated).unsqueeze(1)

In [9]:
state.size()

torch.Size([32, 4, 10, 10])

In [10]:
action.size()

torch.Size([32, 1])

In [17]:
q_value = my_agent.policy_model(state).gather(1, action)

next_q_values = my_agent.target_model(next_state).detach()
next_q_value = next_q_values.max(1)[0].unsqueeze(1)

expected_q_value = reward + my_agent.gamma * next_q_value * (1 - terminated)
# expected_q_value = torch.unsqueeze(expected_q_value, 1)

loss = (q_value - expected_q_value).pow(2).mean()

In [18]:
loss

tensor(0.0969, grad_fn=<MeanBackward0>)

In [29]:
q_value = my_agent.policy_model(state)
q_value

tensor([[-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0463, -0.0590, -0.0196,  0.0600, -0.0618,  0.0527],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0629, -0.0603,  0.0530],
        [-0.0438, -0.0587, -0.0161,  0.0

In [44]:
q_value.size()

torch.Size([32, 1])

In [45]:
action.unsqueeze(0).size()

torch.Size([1, 32])

In [71]:
q_value = my_agent.policy_model(state).gather(1, action.unsqueeze(1))

In [72]:
q_value.size()

torch.Size([32, 1])

In [73]:
next_q_values = my_agent.target_model(next_state).detach()
next_q_value = next_q_values.max(1)[0].unsqueeze(1)

In [74]:
next_q_value.size()

torch.Size([32, 1])

In [83]:
terminated.size()

torch.Size([32])

In [81]:
reward.unsqueeze(1).size()

torch.Size([32, 1])

In [84]:
expected_q_value = reward.unsqueeze(1) + my_agent.gamma * next_q_value * (1 - terminated.unsqueeze(1))
# expected_q_value = torch.unsqueeze(expected_q_value, 1)
expected_q_value

tensor([[0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429]])

In [85]:
expected_q_value.size()

torch.Size([32, 1])

In [86]:
loss = (q_value - expected_q_value).pow(2).mean()

In [87]:
loss

tensor(0.0049, grad_fn=<MeanBackward0>)

In [95]:
state, action, reward, next_state, terminated = sample



In [122]:
state, action, reward, next_state, terminated = sample

state = torch.from_numpy(state)
next_state = torch.from_numpy(next_state)
action = torch.LongTensor(action).unsqueeze(1)
reward = torch.FloatTensor(reward).unsqueeze(1)
terminated = torch.FloatTensor(terminated).unsqueeze(1)

In [123]:
q_value = my_agent.policy_model(state).gather(1, action)
q_value.size()

torch.Size([32, 1])

In [126]:
next_q_values = my_agent.target_model(next_state).detach()
next_q_values = next_q_values.max(1)[0].unsqueeze(1)
expected_q_value = reward + my_agent.gamma * next_q_values * (1 - terminated)
expected_q_value.size()

torch.Size([32, 1])

In [130]:
loss = f.smooth_l1_loss(expected_q_value, q_value)
loss


tensor(0.0024, grad_fn=<SmoothL1LossBackward0>)

In [116]:
Q_s_prime_a_prime = torch.zeros(len(state), 1)
if len(none_terminal_next_states) != 0:
    Q_s_prime_a_prime[none_terminal_next_state_index] = my_agent.target_model(none_terminal_next_states).detach().max(1)[0].unsqueeze(1)
Q_s_prime_a_prime.size()

torch.Size([32, 1])

In [118]:
target = reward + 0.99 * Q_s_prime_a_prime
target

tensor([[0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429],
        [0.0429]])

In [120]:
import torch.nn.functional as f

loss = f.smooth_l1_loss(target, Q_s_a)


In [121]:
loss

tensor(0.0024, grad_fn=<SmoothL1LossBackward0>)