In [36]:
import os
import torch
from torch import nn
import torch.nn.utils.prune as prune
import torch.nn.functional as F

from minatar import Environment

from my_dqn import Conv_QNET

In [37]:
game = "breakout"
env = Environment(game)

proj_dir = os.path.abspath(".")
default_save_folder = os.path.join(proj_dir, "checkpoints", game)
file_name = os.path.join(default_save_folder, game + "_model")

state_shape = env.state_shape()

in_features = (state_shape[2], state_shape[0], state_shape[1])
in_channels = in_features[0]
num_actions = env.num_actions()

model = Conv_QNET(in_features, in_channels, num_actions)
# checkpoint = torch.load(file_name)
# model.load_state_dict(checkpoint["policy_model_state_dict"])


In [38]:
in_features

(4, 10, 10)

In [4]:
module = model.features[0]
print(list(module.named_parameters())) # contains weights and biases
# print(list(module.named_buffers()))

[('weight', Parameter containing:
tensor([[[[ 0.0659, -0.1499, -0.0302],
          [ 0.1369, -0.0479,  0.1248],
          [ 0.0132, -0.0921,  0.1108]],

         [[-0.1398,  0.0166,  0.1013],
          [-0.0023, -0.0939,  0.1633],
          [ 0.1184,  0.0621,  0.1172]],

         [[ 0.1647, -0.0522, -0.1057],
          [ 0.1419, -0.0343, -0.1584],
          [ 0.1015,  0.0611,  0.1528]],

         [[-0.1534,  0.0868,  0.1099],
          [-0.0140, -0.0388,  0.0737],
          [ 0.0507,  0.1321,  0.0193]]],


        [[[ 0.1071, -0.1104,  0.1132],
          [ 0.1522,  0.0296,  0.0933],
          [ 0.1311, -0.1033,  0.1515]],

         [[-0.0742, -0.0330,  0.0952],
          [ 0.1079, -0.0233, -0.0577],
          [-0.0330,  0.0717, -0.0036]],

         [[ 0.0943, -0.1078,  0.0957],
          [ 0.1087,  0.0862,  0.0176],
          [-0.1640, -0.0969, -0.0323]],

         [[-0.1384, -0.1427, -0.0439],
          [-0.1355,  0.1070, -0.1497],
          [ 0.0363,  0.1412,  0.1173]]],


        [[

In [5]:
print(list(module.named_modules()))

[('', Conv2d(4, 16, kernel_size=(3, 3), stride=(1, 1)))]


In [6]:
prune.random_unstructured(module, name="weight", amount=0.3)

Conv2d(4, 16, kernel_size=(3, 3), stride=(1, 1))

In [7]:
print(list(module.named_parameters()))

[('bias', Parameter containing:
tensor([ 0.1410, -0.0647,  0.0736,  0.0949,  0.0799, -0.1207, -0.0145,  0.0371,
         0.1489,  0.0041,  0.0048, -0.0505, -0.0566,  0.0342, -0.1200,  0.1447],
       requires_grad=True)), ('weight_orig', Parameter containing:
tensor([[[[ 0.0659, -0.1499, -0.0302],
          [ 0.1369, -0.0479,  0.1248],
          [ 0.0132, -0.0921,  0.1108]],

         [[-0.1398,  0.0166,  0.1013],
          [-0.0023, -0.0939,  0.1633],
          [ 0.1184,  0.0621,  0.1172]],

         [[ 0.1647, -0.0522, -0.1057],
          [ 0.1419, -0.0343, -0.1584],
          [ 0.1015,  0.0611,  0.1528]],

         [[-0.1534,  0.0868,  0.1099],
          [-0.0140, -0.0388,  0.0737],
          [ 0.0507,  0.1321,  0.0193]]],


        [[[ 0.1071, -0.1104,  0.1132],
          [ 0.1522,  0.0296,  0.0933],
          [ 0.1311, -0.1033,  0.1515]],

         [[-0.0742, -0.0330,  0.0952],
          [ 0.1079, -0.0233, -0.0577],
          [-0.0330,  0.0717, -0.0036]],

         [[ 0.0943, -0.1

In [8]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[1., 1., 1.],
          [1., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [0., 1., 1.],
          [1., 0., 0.]],

         [[1., 0., 0.],
          [0., 0., 0.],
          [1., 1., 0.]]],


        [[[1., 0., 0.],
          [1., 1., 1.],
          [0., 1., 1.]],

         [[0., 0., 0.],
          [1., 0., 1.],
          [1., 1., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [0., 1., 0.]],

         [[1., 1., 0.],
          [0., 0., 1.],
          [0., 1., 1.]]],


        [[[1., 1., 1.],
          [0., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [0., 1., 1.],
          [1., 1., 0.]],

         [[1., 1., 0.],
          [1., 1., 0.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [0., 1., 0.],
          [1., 1., 1.]]],


        [[[1., 0., 1.],
          [1., 0., 1.],
          [1., 1., 1.]],

         [[1., 

In [9]:
print(module.weight)

tensor([[[[ 0.0659, -0.1499, -0.0302],
          [ 0.1369, -0.0479,  0.0000],
          [ 0.0000, -0.0000,  0.1108]],

         [[-0.1398,  0.0000,  0.1013],
          [-0.0023, -0.0939,  0.1633],
          [ 0.1184,  0.0621,  0.1172]],

         [[ 0.1647, -0.0522, -0.1057],
          [ 0.0000, -0.0343, -0.1584],
          [ 0.1015,  0.0000,  0.0000]],

         [[-0.1534,  0.0000,  0.0000],
          [-0.0000, -0.0000,  0.0000],
          [ 0.0507,  0.1321,  0.0000]]],


        [[[ 0.1071, -0.0000,  0.0000],
          [ 0.1522,  0.0296,  0.0933],
          [ 0.0000, -0.1033,  0.1515]],

         [[-0.0000, -0.0000,  0.0000],
          [ 0.1079, -0.0000, -0.0577],
          [-0.0330,  0.0717, -0.0000]],

         [[ 0.0943, -0.1078,  0.0957],
          [ 0.1087,  0.0862,  0.0176],
          [-0.0000, -0.0969, -0.0000]],

         [[-0.1384, -0.1427, -0.0000],
          [-0.0000,  0.0000, -0.1497],
          [ 0.0000,  0.1412,  0.1173]]],


        [[[-0.0163,  0.0721, -0.1167],
     

In [10]:
print(module._forward_pre_hooks)

OrderedDict([(0, <torch.nn.utils.prune.RandomUnstructured object at 0x0000029FD6F265C0>)])


In [11]:
prune.l1_unstructured(module, name="bias", amount=3)

Conv2d(4, 16, kernel_size=(3, 3), stride=(1, 1))

In [12]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 0.0659, -0.1499, -0.0302],
          [ 0.1369, -0.0479,  0.1248],
          [ 0.0132, -0.0921,  0.1108]],

         [[-0.1398,  0.0166,  0.1013],
          [-0.0023, -0.0939,  0.1633],
          [ 0.1184,  0.0621,  0.1172]],

         [[ 0.1647, -0.0522, -0.1057],
          [ 0.1419, -0.0343, -0.1584],
          [ 0.1015,  0.0611,  0.1528]],

         [[-0.1534,  0.0868,  0.1099],
          [-0.0140, -0.0388,  0.0737],
          [ 0.0507,  0.1321,  0.0193]]],


        [[[ 0.1071, -0.1104,  0.1132],
          [ 0.1522,  0.0296,  0.0933],
          [ 0.1311, -0.1033,  0.1515]],

         [[-0.0742, -0.0330,  0.0952],
          [ 0.1079, -0.0233, -0.0577],
          [-0.0330,  0.0717, -0.0036]],

         [[ 0.0943, -0.1078,  0.0957],
          [ 0.1087,  0.0862,  0.0176],
          [-0.1640, -0.0969, -0.0323]],

         [[-0.1384, -0.1427, -0.0439],
          [-0.1355,  0.1070, -0.1497],
          [ 0.0363,  0.1412,  0.1173]]],


     

In [13]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[1., 1., 1.],
          [1., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [0., 1., 1.],
          [1., 0., 0.]],

         [[1., 0., 0.],
          [0., 0., 0.],
          [1., 1., 0.]]],


        [[[1., 0., 0.],
          [1., 1., 1.],
          [0., 1., 1.]],

         [[0., 0., 0.],
          [1., 0., 1.],
          [1., 1., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [0., 1., 0.]],

         [[1., 1., 0.],
          [0., 0., 1.],
          [0., 1., 1.]]],


        [[[1., 1., 1.],
          [0., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [0., 1., 1.],
          [1., 1., 0.]],

         [[1., 1., 0.],
          [1., 1., 0.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [0., 1., 0.],
          [1., 1., 1.]]],


        [[[1., 0., 1.],
          [1., 0., 1.],
          [1., 1., 1.]],

         [[1., 

In [14]:
print(module.bias)

tensor([ 0.1410, -0.0647,  0.0736,  0.0949,  0.0799, -0.1207, -0.0000,  0.0371,
         0.1489,  0.0000,  0.0000, -0.0505, -0.0566,  0.0342, -0.1200,  0.1447],
       grad_fn=<MulBackward0>)


In [15]:
print(module._forward_pre_hooks)

OrderedDict([(0, <torch.nn.utils.prune.RandomUnstructured object at 0x0000029FD6F265C0>), (1, <torch.nn.utils.prune.L1Unstructured object at 0x0000029FD6F26560>)])


### Iterative Pruning

In [16]:
prune.ln_structured(module, name="weight", amount=0.5, n=2, dim=0)

# As we can verify, this will zero out all the connections corresponding to
# 50% (3 out of 6) of the channels, while preserving the action of the
# previous mask.
print(module.weight)

tensor([[[[ 0.0659, -0.1499, -0.0302],
          [ 0.1369, -0.0479,  0.0000],
          [ 0.0000, -0.0000,  0.1108]],

         [[-0.1398,  0.0000,  0.1013],
          [-0.0023, -0.0939,  0.1633],
          [ 0.1184,  0.0621,  0.1172]],

         [[ 0.1647, -0.0522, -0.1057],
          [ 0.0000, -0.0343, -0.1584],
          [ 0.1015,  0.0000,  0.0000]],

         [[-0.1534,  0.0000,  0.0000],
          [-0.0000, -0.0000,  0.0000],
          [ 0.0507,  0.1321,  0.0000]]],


        [[[ 0.1071, -0.0000,  0.0000],
          [ 0.1522,  0.0296,  0.0933],
          [ 0.0000, -0.1033,  0.1515]],

         [[-0.0000, -0.0000,  0.0000],
          [ 0.1079, -0.0000, -0.0577],
          [-0.0330,  0.0717, -0.0000]],

         [[ 0.0943, -0.1078,  0.0957],
          [ 0.1087,  0.0862,  0.0176],
          [-0.0000, -0.0969, -0.0000]],

         [[-0.1384, -0.1427, -0.0000],
          [-0.0000,  0.0000, -0.1497],
          [ 0.0000,  0.1412,  0.1173]]],


        [[[-0.0163,  0.0721, -0.1167],
     

In [20]:
for hook in module._forward_pre_hooks.values():
    if hook._tensor_name == "weight":  # select out the correct hook
        break

print(list(hook)) 
# print(hook)

[<torch.nn.utils.prune.RandomUnstructured object at 0x0000029FD6F265C0>, <torch.nn.utils.prune.LnStructured object at 0x0000029FD6F25C60>]


In [21]:
print(model.state_dict().keys())

odict_keys(['features.0.weight_orig', 'features.0.bias_orig', 'features.0.weight_mask', 'features.0.bias_mask', 'fc.0.weight', 'fc.0.bias', 'fc.2.weight', 'fc.2.bias'])


In [22]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 0.0659, -0.1499, -0.0302],
          [ 0.1369, -0.0479,  0.1248],
          [ 0.0132, -0.0921,  0.1108]],

         [[-0.1398,  0.0166,  0.1013],
          [-0.0023, -0.0939,  0.1633],
          [ 0.1184,  0.0621,  0.1172]],

         [[ 0.1647, -0.0522, -0.1057],
          [ 0.1419, -0.0343, -0.1584],
          [ 0.1015,  0.0611,  0.1528]],

         [[-0.1534,  0.0868,  0.1099],
          [-0.0140, -0.0388,  0.0737],
          [ 0.0507,  0.1321,  0.0193]]],


        [[[ 0.1071, -0.1104,  0.1132],
          [ 0.1522,  0.0296,  0.0933],
          [ 0.1311, -0.1033,  0.1515]],

         [[-0.0742, -0.0330,  0.0952],
          [ 0.1079, -0.0233, -0.0577],
          [-0.0330,  0.0717, -0.0036]],

         [[ 0.0943, -0.1078,  0.0957],
          [ 0.1087,  0.0862,  0.0176],
          [-0.1640, -0.0969, -0.0323]],

         [[-0.1384, -0.1427, -0.0439],
          [-0.1355,  0.1070, -0.1497],
          [ 0.0363,  0.1412,  0.1173]]],


     

In [23]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[1., 1., 1.],
          [1., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [0., 1., 1.],
          [1., 0., 0.]],

         [[1., 0., 0.],
          [0., 0., 0.],
          [1., 1., 0.]]],


        [[[1., 0., 0.],
          [1., 1., 1.],
          [0., 1., 1.]],

         [[0., 0., 0.],
          [1., 0., 1.],
          [1., 1., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [0., 1., 0.]],

         [[1., 1., 0.],
          [0., 0., 1.],
          [0., 1., 1.]]],


        [[[1., 1., 1.],
          [0., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [0., 1., 1.],
          [1., 1., 0.]],

         [[1., 1., 0.],
          [1., 1., 0.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [0., 1., 0.],
          [1., 1., 1.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 

In [24]:
print(module.weight)

tensor([[[[ 0.0659, -0.1499, -0.0302],
          [ 0.1369, -0.0479,  0.0000],
          [ 0.0000, -0.0000,  0.1108]],

         [[-0.1398,  0.0000,  0.1013],
          [-0.0023, -0.0939,  0.1633],
          [ 0.1184,  0.0621,  0.1172]],

         [[ 0.1647, -0.0522, -0.1057],
          [ 0.0000, -0.0343, -0.1584],
          [ 0.1015,  0.0000,  0.0000]],

         [[-0.1534,  0.0000,  0.0000],
          [-0.0000, -0.0000,  0.0000],
          [ 0.0507,  0.1321,  0.0000]]],


        [[[ 0.1071, -0.0000,  0.0000],
          [ 0.1522,  0.0296,  0.0933],
          [ 0.0000, -0.1033,  0.1515]],

         [[-0.0000, -0.0000,  0.0000],
          [ 0.1079, -0.0000, -0.0577],
          [-0.0330,  0.0717, -0.0000]],

         [[ 0.0943, -0.1078,  0.0957],
          [ 0.1087,  0.0862,  0.0176],
          [-0.0000, -0.0969, -0.0000]],

         [[-0.1384, -0.1427, -0.0000],
          [-0.0000,  0.0000, -0.1497],
          [ 0.0000,  0.1412,  0.1173]]],


        [[[-0.0163,  0.0721, -0.1167],
     

In [25]:
prune.remove(module, 'weight')
print(list(module.named_parameters()))

[('bias_orig', Parameter containing:
tensor([ 0.1410, -0.0647,  0.0736,  0.0949,  0.0799, -0.1207, -0.0145,  0.0371,
         0.1489,  0.0041,  0.0048, -0.0505, -0.0566,  0.0342, -0.1200,  0.1447],
       requires_grad=True)), ('weight', Parameter containing:
tensor([[[[ 0.0659, -0.1499, -0.0302],
          [ 0.1369, -0.0479,  0.0000],
          [ 0.0000, -0.0000,  0.1108]],

         [[-0.1398,  0.0000,  0.1013],
          [-0.0023, -0.0939,  0.1633],
          [ 0.1184,  0.0621,  0.1172]],

         [[ 0.1647, -0.0522, -0.1057],
          [ 0.0000, -0.0343, -0.1584],
          [ 0.1015,  0.0000,  0.0000]],

         [[-0.1534,  0.0000,  0.0000],
          [-0.0000, -0.0000,  0.0000],
          [ 0.0507,  0.1321,  0.0000]]],


        [[[ 0.1071, -0.0000,  0.0000],
          [ 0.1522,  0.0296,  0.0933],
          [ 0.0000, -0.1033,  0.1515]],

         [[-0.0000, -0.0000,  0.0000],
          [ 0.1079, -0.0000, -0.0577],
          [-0.0330,  0.0717, -0.0000]],

         [[ 0.0943, -0.1

In [26]:
print(list(module.named_buffers()))

[('bias_mask', tensor([1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1.]))]


In [27]:
in_features = (state_shape[2], state_shape[0], state_shape[1])
in_channels = in_features[0]
num_actions = env.num_actions()

model = Conv_QNET(in_features, in_channels, num_actions)

for name, module in model.named_modules():
    # prune 20% of connections in all 2D-conv layers
    if isinstance(module, torch.nn.Conv2d):
        prune.l1_unstructured(module, name='weight', amount=0.2)
    # prune 40% of connections in all linear layers
    elif isinstance(module, torch.nn.Linear):
        prune.l1_unstructured(module, name='weight', amount=0.4)

print(dict(model.named_buffers()).keys())  # to verify that all masks exist

dict_keys(['features.0.bias_mask', 'features.0.weight_mask', 'fc.0.weight_mask', 'fc.2.weight_mask'])


### Global pruning

In [30]:
in_features = (state_shape[2], state_shape[0], state_shape[1])
in_channels = in_features[0]
num_actions = env.num_actions()

model = Conv_QNET(in_features, in_channels, num_actions)

parameters_to_prune = (
    (model.features[0], 'weight'),
    (model.fc[0], 'weight'),
    (model.fc[2], 'weight'),

)

prune.global_unstructured(
    parameters_to_prune,
    pruning_method=prune.L1Unstructured,
    amount=0.2,
)

In [31]:
print(
    "Sparsity in features[0].weight: {:.2f}%".format(
        100. * float(torch.sum(model.features[0].weight == 0))
        / float(model.features[0].weight.nelement())
    )
)
print(
    "Sparsity in fc[0].weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc[0].weight == 0))
        / float(model.fc[0].weight.nelement())
    )
)
print(
    "Sparsity in fc[2].weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc[2].weight == 0))
        / float(model.fc[2].weight.nelement())
    )
)

Sparsity in features[0].weight: 3.65%
Sparsity in fc[0].weight: 20.15%
Sparsity in fc[2].weight: 6.90%


In [33]:
class FooBarPruningMethod(prune.BasePruningMethod):
    """Prune every other entry in a tensor
    """
    PRUNING_TYPE = 'unstructured'

    def compute_mask(self, t, default_mask):
        mask = default_mask.clone()
        mask.view(-1)[::2] = 0
        return mask

def foobar_unstructured(module, name):
    """Prunes tensor corresponding to parameter called `name` in `module`
    by removing every other entry in the tensors.
    Modifies module in place (and also return the modified module)
    by:
    1) adding a named buffer called `name+'_mask'` corresponding to the
    binary mask applied to the parameter `name` by the pruning method.
    The parameter `name` is replaced by its pruned version, while the
    original (unpruned) parameter is stored in a new parameter named
    `name+'_orig'`.

    Args:
        module (nn.Module): module containing the tensor to prune
        name (string): parameter name within `module` on which pruning
                will act.

    Returns:
        module (nn.Module): modified (i.e. pruned) version of the input
            module

    Examples:
        >>> m = nn.Linear(3, 4)
        >>> foobar_unstructured(m, name='bias')
    """
    FooBarPruningMethod.apply(module, name)
    return module

In [35]:
in_features = (state_shape[2], state_shape[0], state_shape[1])
in_channels = in_features[0]
num_actions = env.num_actions()

model = Conv_QNET(in_features, in_channels, num_actions)

foobar_unstructured(model.features[0], name='bias')

print(model.features[0].bias_mask)

tensor([0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.])


In [24]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torch.autograd as autograd

import torch.nn.utils.prune as prune

from minatar import Environment

import seaborn as sns
import matplotlib.pyplot as plt

# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device = "cpu"


class Min_Net(nn.Module):
    def __init__(self):
        super().__init__()

        self.channels = 4
        
        # conv layers
        self.conv_l = nn.Conv2d(self.channels, 5, kernel_size=3, stride=1)

        self.fc = nn.Linear(5 * 6 * 6, 64)

    def forward(self, x):
        x = x.float()
        x = self.conv_l(x)
        x = x.reshape(x.size(0), -1)
        x = self.fc(x)
        return x


In [56]:

ex_net = Min_Net()
ex_net

ex_in = torch.rand(1, 4, 8, 8)
ex_net(ex_in)

module = ex_net.conv_l
print(list(module.named_parameters()))
# print(list(module.named_modules()))

[('weight', Parameter containing:
tensor([[[[-0.0383,  0.1417,  0.1158],
          [ 0.0899, -0.0011,  0.0128],
          [-0.1659,  0.0194, -0.0947]],

         [[-0.0273, -0.0345, -0.1110],
          [ 0.0063, -0.1318,  0.0883],
          [-0.0144,  0.0580,  0.0871]],

         [[ 0.1032, -0.0299,  0.0252],
          [-0.1361, -0.1049, -0.1564],
          [-0.1392,  0.0864,  0.0935]],

         [[-0.0827, -0.0533, -0.1210],
          [-0.1095, -0.0627, -0.0996],
          [ 0.0849,  0.0418,  0.0314]]],


        [[[-0.0976, -0.1192,  0.0512],
          [ 0.0674,  0.0838,  0.0326],
          [ 0.0669,  0.0150, -0.0528]],

         [[ 0.1608,  0.0767, -0.0063],
          [-0.0618,  0.0508,  0.0310],
          [ 0.0210,  0.1593,  0.0623]],

         [[-0.0294,  0.0515,  0.1572],
          [-0.0589, -0.0447,  0.0079],
          [-0.1634,  0.1320, -0.0892]],

         [[ 0.0316, -0.1216,  0.1211],
          [-0.0927,  0.1595, -0.1321],
          [-0.0925,  0.1625, -0.0615]]],


        [[

In [57]:
module.weight.shape

torch.Size([5, 4, 3, 3])

In [58]:
# prune.random_unstructured(module, name="weight", amount=0.25)
# prune.l1_unstructured(module, name="weight", amount=0.25)
prune.ln_structured(module, name="weight", amount=0.5, n=2, dim=0)

print(list(module.named_parameters()))


[('bias', Parameter containing:
tensor([-0.0775, -0.1653, -0.1231,  0.0825, -0.1158], requires_grad=True)), ('weight_orig', Parameter containing:
tensor([[[[-0.0383,  0.1417,  0.1158],
          [ 0.0899, -0.0011,  0.0128],
          [-0.1659,  0.0194, -0.0947]],

         [[-0.0273, -0.0345, -0.1110],
          [ 0.0063, -0.1318,  0.0883],
          [-0.0144,  0.0580,  0.0871]],

         [[ 0.1032, -0.0299,  0.0252],
          [-0.1361, -0.1049, -0.1564],
          [-0.1392,  0.0864,  0.0935]],

         [[-0.0827, -0.0533, -0.1210],
          [-0.1095, -0.0627, -0.0996],
          [ 0.0849,  0.0418,  0.0314]]],


        [[[-0.0976, -0.1192,  0.0512],
          [ 0.0674,  0.0838,  0.0326],
          [ 0.0669,  0.0150, -0.0528]],

         [[ 0.1608,  0.0767, -0.0063],
          [-0.0618,  0.0508,  0.0310],
          [ 0.0210,  0.1593,  0.0623]],

         [[-0.0294,  0.0515,  0.1572],
          [-0.0589, -0.0447,  0.0079],
          [-0.1634,  0.1320, -0.0892]],

         [[ 0.0316,

In [59]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 

In [52]:
pruned_mask = list(module.named_buffers())[0][1]
pruned_mask.size()

torch.Size([5, 4, 3, 3])

In [55]:
pruned_mask[2]

tensor([[[1., 1., 1.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [170]:
game = "breakout"
env = Environment(game)

proj_dir = os.path.abspath(".")
default_save_folder = os.path.join(proj_dir, "checkpoints", game)
file_name = os.path.join(default_save_folder, game + "_model")

state_shape = env.state_shape()

in_features = (state_shape[2], state_shape[0], state_shape[1])
in_channels = in_features[0]
num_actions = env.num_actions()

model = Conv_QNET(in_features, in_channels, num_actions)

for name, module in model.named_modules():
    # prune 20% of connections in all 2D-conv layers
    if isinstance(module, torch.nn.Conv2d):
        prune.ln_structured(module, name="weight", amount=0.1, n=2, dim=1)
        
    # prune 40% of connections in all linear layers
    elif isinstance(module, torch.nn.Linear):
        prune.l1_unstructured(module, name='weight', amount=0.1)
        


<generator object Module.parameters at 0x0000029FDEF73220>
<generator object Module.parameters at 0x0000029FDEF73220>
<generator object Module.parameters at 0x0000029FDEF73220>


In [163]:
for name, module in model.named_modules():
    
    print(isinstance(module, torch.nn.Sequential))

False
False
False
False
False
False
False
False


In [164]:
list(model.named_modules())

[('',
  Conv_QNET(
    (features): Sequential(
      (0): Conv2d(4, 16, kernel_size=(3, 3), stride=(1, 1))
      (1): ReLU()
    )
    (fc): Sequential(
      (0): Linear(in_features=1024, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=6, bias=True)
    )
  )),
 ('features',
  Sequential(
    (0): Conv2d(4, 16, kernel_size=(3, 3), stride=(1, 1))
    (1): ReLU()
  )),
 ('features.0', Conv2d(4, 16, kernel_size=(3, 3), stride=(1, 1))),
 ('features.1', ReLU()),
 ('fc',
  Sequential(
    (0): Linear(in_features=1024, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=6, bias=True)
  )),
 ('fc.0', Linear(in_features=1024, out_features=128, bias=True)),
 ('fc.1', ReLU()),
 ('fc.2', Linear(in_features=128, out_features=6, bias=True))]

In [168]:
for name, module in model.named_modules():
    print(name, type(module))

 <class 'my_dqn.Conv_QNET'>
features <class 'torch.nn.modules.container.Sequential'>
features.0 <class 'torch.nn.modules.conv.Conv2d'>
features.1 <class 'torch.nn.modules.activation.ReLU'>
fc <class 'torch.nn.modules.container.Sequential'>
fc.0 <class 'torch.nn.modules.linear.Linear'>
fc.1 <class 'torch.nn.modules.activation.ReLU'>
fc.2 <class 'torch.nn.modules.linear.Linear'>


In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [20]:
import os
from viz_helper import load_pruning_experiment_data

game = "breakout"
proj_dir = os.path.abspath('.')
default_save_folder = os.path.join(proj_dir, "checkpoints", game)
train_log_file_name = os.path.join(default_save_folder, game + "_train_stats")

baseline_file_path = os.path.join(default_save_folder, "pruning_exp", "baseline")
pruning_log_file_name = os.path.join(default_save_folder, "pruning_exp", "pruning_results_1")

# plot_training_info(train_log_file_name)
baseline_stats, baseline_info = load_pruning_experiment_data(baseline_file_path)
pruning_stats, exp_info = load_pruning_experiment_data(pruning_log_file_name)

In [21]:
baseline_stats

{0.0: {'episode_rewards': {'min': 2.0,
   'max': 159.0,
   'mean': 50.214285714285715,
   'median': 35.5,
   'std': 35.61496188688234},
  'episode_frames': {'min': 28,
   'max': 2984,
   'mean': 716.8285714285714,
   'median': 474.0,
   'std': 589.9385433229119},
  'episode_max_qs': {'min': 3.592989921569824,
   'max': 15.68076229095459,
   'mean': 7.932367863949765,
   'median': 6.536515712738037,
   'std': 3.650602237282145},
  'epoch_time': datetime.timedelta(seconds=9, microseconds=223722)}}

In [15]:
pruning_stats[0.4]

{'episode_rewards': {'min': 0.0,
  'max': 121.0,
  'mean': 13.72,
  'median': 7.5,
  'std': 15.210794412740798},
 'episode_frames': {'min': 6,
  'max': 1610,
  'mean': 167.42666666666668,
  'median': 87.0,
  'std': 216.36664396857068},
 'episode_max_qs': {'min': nan,
  'max': nan,
  'mean': nan,
  'median': nan,
  'std': nan},
 'epoch_time': datetime.timedelta(seconds=15, microseconds=301182)}

In [11]:
# pruning_stats
exp_info

'Prune the first convolutional layer and the first linear layer in the output layer using unstructured pruning with L1 norm.'

In [10]:
import pandas as pd 

x_idx = []
stat_records = []
metric = "episode_rewards"

for pruning_val in stats:
    x_idx.append(pruning_val)
    stat_records.append(stats[pruning_val][metric])

df = pd.DataFrame.from_records(stat_records, index = x_idx) 
df = df.reset_index()
df = df.rename(columns = {'index': 'pruning_factor'})

df

pruning_factor  min    max       mean  median        std
0            0.00  3.0  235.0  45.853333    29.0  36.306728
1            0.05  0.0  114.0  35.515789    26.0  24.906504
2            0.10  0.0    9.0   1.799279     1.0   2.127646
3            0.15  0.0    5.0   0.652196     1.0   0.740875
4            0.20  0.0    8.0   3.795247     4.0   1.500803
5            0.30  0.0   15.0   4.102616     5.0   2.329829
6            0.40  0.0    4.0   0.764207     0.0   0.969910
7            0.50  0.0    5.0   0.316309     0.0   0.859596